### ISSUE TITLE
Create new custom Action filter to run input model validation 

### ISSUE THREAD

**Issue by roman-fay** [ss-ita/gtd-timer-server#10]
https://github.com/ss-ita/gtd-timer-server/blob/0f30f9b2071bafa762910dc164ea300f3a101760/gtd-timer/Controllers/SignUpController.cs#L38

We **do** have validation attributes added to UserDto. The problem is that we are not checking Model validity in controller itself. So current flow is like this:

1. Let's say user doesn't provide one of required params
2. Validation attributes do their job - and mark model as invalid.
3. Because we are not checking anything in controller - execution resumes and will eventually fail anyway.

Fixing this is as simple as adding
 if (!ModelState.IsValid){ throw new Exception... }
to controller.

But, since this line should be in every and each controller we'll create, let's implement it a bit more 'centralized'.
I'm thinking about creating new custom action filter (inherited from ActionFilterAttribute) with AttributeTargets.Method | AttributeTargets.Class, named something like [ValidateInput] and adding that logic there.

**Comment by nataliapachva** [comment]
Done. 
Could you please review?
