### ISSUE TITLE
Property recursion

### ISSUE THREAD

**Issue by roman-fay** [ss-ita/gtd-timer-server#41]
https://github.com/ss-ita/gtd-timer-server/blob/654c2da3aebc27bd3fde41975e248fd441ec0c5e/Timer.DAL/Timer.DAL/UnitOfWork/UnitOfWork.cs#L35

Actually using this property (which I assume we never did or tested) will lead to StackoverflowException.
Roles property get returns Roles property and so on. Proper way is to add backing field to this.

**Comment by TarasKataryna** [comment]
I changed it and i have to do new pull request now, right?

**Comment by roman-fay** [comment]
right
